---
- hosts: localhost
  tasks:
    - add_host: name="{{ item }}" groups="kube_nodes,kube_master,kube_minions"
      with_items: groups.controller
      when: stack_type == "kubernetes"
    - add_host: name="{{ item }}" groups="kube_nodes,kube_minions"
      with_items: groups.computes
      when: stack_type == "kubernetes"

- hosts: kube_nodes
  roles:
    - stack/kubernetes/prep

- hosts: kube_master
  roles:
    - stack/kubernetes/install-master

- hosts: kube_minions
  roles:
    - stack/kubernetes/install-minion

- hosts: kube_master
  roles:
    - stack/kubernetes/postinstall
