---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: romana-route-publisher
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        romana-app: route-publisher
    spec:
      hostNetwork: true
      hostPID: true
      securityContext:
        seLinuxOptions:
          type: spc_t
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: publisher
        image: quay.io/romana/x-route-publisher:v2.0-preview.3
        imagePullPolicy: Always
        args:
        - --asn=65534
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: run-path
          mountPath: /var/run/romana
      - name: bird
        image: quay.io/romana/x-bird:v2.0-preview.3
        imagePullPolicy: Always
        args:
        - --config-dir=/var/tmp/romana/publisher-config
        - --bird-config=bird.conf
        - --publisher-template=publisher.conf
        env:
        - name: NODEIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          privileged: true
        volumeMounts:
        - name: route-publisher-config
          mountPath: /var/tmp/romana/publisher-config
        - name: run-path
          mountPath: /var/run/romana
      volumes:
      - name: route-publisher-config
        configMap:
          name: route-publisher-config
      - name: run-path
        emptyDir: {}
