---
- name: Fetch the etcd release
  get_url: url="{{ etcd_url }}" dest="{{ kubernetes_dl_dir}}/etcd.tar.gz" mode=0644
  register: dl

- debug: var=dl

- name: Validate the downloaded file
  stat: path="{{ kubernetes_dl_dir}}/etcd.tar.gz"
  register: k
  when: dl.changed
  failed_when: k.stat.checksum != "{{ etcd_sha1 }}"

- name: Extract files
  unarchive: copy=no src="{{ kubernetes_dl_dir}}/etcd.tar.gz" dest="{{ kubernetes_x_dir}}/"
  when: dl.changed
