---
- name: etcd binaries
  command: install -o root -g root -m 0755 {{ kubernetes_x_dir }}/etcd-v{{ etcd_version }}-linux-amd64/{{ item }} /usr/local/bin/{{ item }}
  args:
    creates: /usr/local/bin/{{ item }}
  with_items:
    - etcd
    - etcdctl
 
- name: etcd config directory
  file: path="/etc/etcd" state="directory"

- name: etcd config file
  template: src="etcd/etcd.conf" dest="/etc/etcd/etcd.conf"

- name: etcd data dir
  file: path="/var/lib/etcd" state="directory"

- name: kubernetes master config files
  template: src="kubernetes/{{ item }}" dest="/etc/kubernetes/{{ item }}"
  with_items:
    - apiserver
    - scheduler
    - controller-manager

- name: kubernetes binaries
  command: install -o root -g root -m 0755 {{ kubernetes_x_dir }}/kubernetes/server/bin/{{ item }} /usr/local/bin/{{ item }}
  args:
    creates: /usr/local/bin/{{ item }}
  with_items:
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
