---
- name: Add Kubernetes yum source
  copy: src="kubernetes.repo" dest="/etc/yum.repos.d/kubernetes.repo"

- name: Disable SELinux enforcement
  command: setenforce 0

- name: Import GPG keys
  command: rpm --import "{{ item }}"
  with_items:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install additional packages
  yum: update_cache=yes pkg="{{ item }}"
  with_items:
    - docker
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
    - mariadb-server
    - python-simplejson
    - python-requests
