---
kind: Pod
apiVersion: v1
metadata:
  name: romana-etcd
  namespace: kube-system
  labels:
    component: romana-etcd
    tier: control-plane
spec:
  hostNetwork: true
  containers:
  - name: romana-etcd
    image: gcr.io/google_containers/etcd-amd64:3.0.4
    command:
    - etcd
    - "--listen-client-urls=http://127.0.0.1:12379"
    - "--listen-peer-urls=http://127.0.0.1:12380"
    - "--advertise-client-urls=http://127.0.0.1:12379"
    - "--data-dir=/var/etcd/data"
    volumeMounts:
    - name: etcd-data
      mountPath: "/var/etcd/data"
    livenessProbe:
      httpGet:
        path: "/health"
        port: 12379
        host: 127.0.0.1
      initialDelaySeconds: 15
      timeoutSeconds: 15
  volumes:
  - name: etcd-data
    hostPath:
      path: "/var/lib/romana/etcd-db"
