services:
  - service: root
    api:
      host: {{ romana_master_ip }}
      port: 9600
  - service: ipam
    api:
      host: {{ romana_master_ip }}
      port: 9601
    config:
      store: 
        type: mysql

        host: 127.0.0.1
        username: root
        password: {{ stack_password }}
        database: ipam
  - service: tenant
    api:
      host: {{ romana_master_ip }}
      port: 9602
    config:
      store: 
        type: mysql
        host: 127.0.0.1
        username: root
        password: {{ stack_password }}
        database: tenant
  - service: topology
    api:
      host: {{ romana_master_ip }}
      port: 9603
    config:
      store: 
        type: mysql
        host: 127.0.0.1
        username: root
        password: {{ stack_password }}
        database: topology
      datacenter: 
        ip_version: 4
        cidr: {{ romana_cidr }}
        host_bits: {{ 16 - romana_cidr | ipaddr('prefix') }}
        tenant_bits: 4
        segment_bits: 4
        endpoint_space_bits: 0
        endpoint_bits: 8
  - service: agent 
    api:
      host: 0.0.0.0
      port: 9604
      hooks:
          - executable: {{ romana_bin_dir }}/agent_proxy_add_policy.sh
            pattern: /policies
            method: POST
            when: before
            output: /var/log/policies-hook.log
          - executable: {{ romana_bin_dir }}/agent_proxy_delete_policy.sh
            pattern: /policies
            method: DELETE
            when: before
            output: /var/log/policies-hook.log
{% if stack_type in [ "devstack", "openstack" ] %}
          - executable: {{ romana_bin_dir }}/agent_dhcp_release.sh
            pattern: /vm
            method: DELETE
            when: before
            output: /var/log/dhcp-release-hook.log
{% endif %}
    config:
      lease_file : "/etc/ethers"
      firewall_provider : "save-restore"
      wait_for_iface_try: 6
      store:
        type: sqlite3
        database: {{ romana_db_dir }}/agent.db
  - service: policy
    api:
      host: {{ romana_master_ip }}
      port: 9605
    config:
      store: 
        type: mysql
        host: 127.0.0.1
        username: root
        password: {{ stack_password }}
        database: policy
{% if stack_type == "kubernetes" %}
  - service: kubernetesListener 
    api:
      host: 0.0.0.0
      port: 9606
    config:
      kubernetes_url : "http://{{ romana_master_ip }}:8080"
      namespace_notification_path: "api/v1/namespaces"
      policy_notification_path_prefix : "apis/extensions/v1beta1/namespaces"
      policy_notification_path_postfix : "networkpolicies"
      segment_label_name: "{{ romana_segment_label_name }}"
      tenant_label_name: "{{ romana_tenant_label_name }}"
{% endif %}
