---
- name: Install private key for user
  copy: src="{{ romana_ssh_key }}" dest="~/.ssh/id_rsa" mode=0600

- name: Install public key for user
  copy: src="{{ romana_ssh_key}}.pub" dest="~/.ssh/id_rsa.pub" mode=0644

- name: Add public key to authorised keys
  authorized_key: user=ubuntu key="{{ item }}" state=present
  with_file:
    - "{{ romana_ssh_key }}.pub"
