---
- name: CNI config directory
  file: path="/etc/cni/net.d" state="directory"
  become: true
  become_user: root

- name: CNI config file
  template: src="romana-k8s-network" dest="/etc/cni/net.d/10-romana.conf"
  become: true
  become_user: root

- name: CNI plugin directory
  file: path="/opt/cni/bin" state="directory"
  become: true
  become_user: root

- name: CNI plugin executable
  become: true
  become_user: root
  get_url: url=https://raw.githubusercontent.com/romana/core/{{ romana_core_branch }}/pkg/cni/romana dest=/opt/cni/bin/romana mode=0755
