---
- name: Add Kubernetes yum source
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM Repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: |
      https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    repo_gpgcheck: yes

- name: Install kubeadm packages
  yum: update_cache="yes" pkg="{{ item }}"
  with_items:
    - docker-io
    - kubelet
    - kubeadm
    - kubernetes-cni

- name: Add docker group
  group: name="docker"

- name: Start docker and kubelet
  service: name="{{ item }}" enabled="yes" state="started"
  with_items:
    - docker
    - kubelet
