---
- name: kubeadm init
  become: true
  become_user: root

  shell: |
         if ! [ -d /var/tmp/kubeadm-init ]; then
             kubeadm init --kubernetes-version {{ kubernetes_version }} --token "{{ kubeadm_token }}" --apiserver-advertise-address="{{ hostvars[groups.kubeadm_master[0]].lan_ip }}" && mkdir /var/tmp/kubeadm-init
         fi

- include: "{{ file }}"
  with_first_found:
    - files:
      - "packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "packages_{{ ansible_distribution|lower }}.yml"
      - "packages_{{ ansible_os_family|lower }}.yml"
      skip: true
  loop_control:
    loop_var: file
  become: true
  become_user: root
