---
- name: Install other service configurations
  template: src="systemd/{{ item }}" dest="/etc/systemd/system/{{ item }}"
  with_items:
    - romana-topology.service
    - romana-tenant.service
    - romana-ipam.service
    - romana-policy.service
    - romana-watchnodes.service
