---
- name: Download binaries
  get_url: url="https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_core_branch }}/{{ item }}" dest="{{ romana_dl_dir }}/{{ item }}" mode=0755
  with_items:
    - listener

- name: Install binaries
  become: true
  become_user: root
  command: install -o root -g root -m 0755 "{{ romana_dl_dir }}/{{ item }}" "{{ romana_bin_dir }}/{{ item }}"
  with_items:
    - listener
 
