---
- include: "kube_listener_from_{{ romana_core_source }}.yml"

- include: "service_configs_{{ ansible_service_mgr }}.yml"
  become: true
  become_user: root

- name: Start services
  service: name="{{ item }}" state="started"
  with_items:
    - romana-kube-listener
    - romana-watchnodes
  become: true
  become_user: root

- include: "demo.yml"
