---
- name: Add Docker apt source
  copy: src=docker.list dest=/etc/apt/sources.list.d/ owner=root group=root mode=0664

- name: Add Docker key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Update apt cache
  apt: update_cache=yes

- name: Ensure other packages are not present
  apt: pkg="{{ item }}" state="absent" purge="yes"
  with_items:
    - lxc-docker
    - docker.io

- name: Install Docker
  apt: pkg="{{ item }}" state=latest
  with_items:
    - docker-engine
