---
- name: Get the romana/kube repository
  git: repo="https://github.com/romana/kube" version="{{ romana_kube_branch }}" dest="{{ kubernetes_x_dir}}/kube"

- name: Install additional packages
  become: true
  become_user: root
  apt: pkg="{{ item }}"
  with_items:
    - python-simplejson
