---
- name: Install base dnsmasq (for dependencies)
  apt: pkg="dnsmasq-base"

- name: Fetch calico modified dnsmasq
  get_url: url="https://s3-us-west-1.amazonaws.com/pani-infrastructure/dist/pre-poc1/dnsmasq-calico" dest="{{ romana_dir }}/bin/dnsmasq-calico" mode=0755

- name: Create /etc/ethers
  file: path="/etc/ethers" state="touch" mode=0644

- name: Create dnsmasq-calico upstart service
  copy: src="dnsmasq-calico.conf" dest="/etc/init/dnsmasq-calico.conf" mode=0644

- name: Enable dnsmasq-calico
  service: name="dnsmasq-calico" state="started"
  
