---
- name: Enable EPEL repository
  yum: pkg="epel-release" state=latest
  when: ansible_distribution|lower == "centos"
  retries: 3

- name: Install additional packages
  yum: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - vim-enhanced
