---
- name: Prep stage before installing Romana binaries
  become: true
  become_user: root
  include: "romana_prep.yml"

- include: network.yml
  become: true
  become_user: root

- include: "romana_from_{{ romana_core_source }}.yml"
- include: "policy_agent.yml"

- include: "{{ file }}"
  with_first_found:
    - files: 
      - "packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "packages_{{ ansible_distribution|lower }}.yml"
      - "packages_{{ ansible_os_family|lower }}.yml"
      skip: true
  loop_control:
    loop_var: file
  become: true
  become_user: root

- include: dnsmasq.yml
  become: true
  become_user: root

- include: "service_configs_{{ ansible_service_mgr }}.yml"
  become: true
  become_user: root

- include: start_services.yml
  become: true
  become_user: root
