- name: Copy files built on master
  command: rsync -az "{{ romana_master_ip }}:/var/tmp/gopath/bin/{{ item }}" "/var/tmp/{{ item }}"
  with_items:
    - agent

- name: Copy policy-agent from master
  command: rsync -az "{{ romana_master_ip }}:/var/tmp/gopath/src/github.com/romana/core/pkg/util/policy/agent/agent.py" "/var/tmp/agent.py"

- name: Install files
  become: true
  become_user: root
  command: install -o root -g root -m 0755 "/var/tmp/{{ item }}" "{{ romana_bin_dir }}/{{ item }}"
  with_items:
    - agent
    - agent.py

- name: Install hook 1
  template: src="config/agent_proxy_add_policy.sh" dest="{{ romana_bin_dir }}/" mode=0777

- name: Install hook 2
  template: src="config/agent_proxy_delete_policy.sh" dest="{{ romana_bin_dir }}/" mode=0777
